#!/bin/sh
set -e
set -u

basedir="$(dirname "$(readlink -e "${0}")")"

if [ $# -lt 1 ]; then
	_tmpdir="template"
	echo -n "Enter target directory [${_tmpdir}]: "
	read targetdir
	if [ -z "${targetdir}" ]; then
		targetdir="${_tmpdir}"
	fi
else
	if [ "${1}" = '-h' ] || [ "${1}" = '--help' ]; then
		echo "USAGE: $(basename "${0}") [TARGETDIRECTORY]"
		echo " Clone docbook-bootstrap template directory and set up a new docbook project directory"
		exit
	fi
	targetdir="${1}"
fi

echo "Supported file formats:"
for i in \
	"Asciidoc:\t\tasciidoc | adoc | ad" \
	"DocBook:\t\tdocbook | dbk" \
	"Markdown:\t\tmarkdown | mkd | md" \
	"Org mode:\t\torg" \
	"reStructuredText:\trst" \
	; do
	echo -e "  ${i}"
done
echo -n "Enter file format [docbook]: "
read format
if [ -z "${format}" ]; then
	format="xml"
fi
case "${format}" in
	docbook | dbk )
		format="xml"
		;;
	asciidoc | adoc | ad )
		format="adoc"
		;;
	markdown | mkd | md )
		format="md"
		;;
	rst )
		format="rst"
		;;
	org )
		format="org"
		;;
	* )
		echo "Unknown format.  Exiting." 1>&2
		exit 1
		;;
esac

if [ -e "${targetdir}" ]; then
	echo "File or directory already exists: ${targetdir}" 1>&2
	exit 1
fi
cp -r "${basedir}/template" "${targetdir}"

targetname="$(basename "${targetdir}")"
sed -i -e "s#^PATH_TO_DBOOTSTRAP=x\$#PATH_TO_DBOOTSTRAP='${basedir}'#" \
	-e "s#^in=.*#in=${targetname}.${format}#" \
	"${targetdir}/Makefile"

rm "${targetdir}/README.adoc"
if [ "${format}" = "xml" ]; then
	mv "${targetdir}/article.xml" "${targetdir}/${targetname}.${format}"
else
	rm "${targetdir}/article.xml"
	touch "${targetdir}/${targetname}.${format}"
fi

set +u
if [ -z "${DOCBOOK_BOOTSTRAP_PATH}" ]; then
	set -u
	echo "Add the following line to your .$(basename "${SHELL}")rc to locate docbook-bootstrap:"
	echo -e "\texport DOCBOOK_BOOTSTRAP_PATH='${basedir}'"
fi
set -u

echo "Clone is ready at '${targetdir}'"
