= DocBook Bootstrap
== Purpose
Setting up a DocBook build environment seems to be extra difficult and
cumbersome.  The goal of this project is to create a platform
independent, easy to depoly environment that brings you to the core
tasks of getting started with THE document within seconds.

.Objectives
- Incorate all the wisdom and hints from
  http://www.docbook.org/tdg51/en/html/
- Be platform independent -> embrace the Java eco-system as much as
  possible
- Make building DocBook documents a breeze

== Setup
0. Get all the additional software (see section Additional Software
   Needed).  Hopefully, you've to do this just once (in a while).
1. Make a copy of the `template` folder and put it where you want to
   create your next document/project.  Adjust the `Makefile` as needed.
3. Start writing your document!
4. Do you need more customization?  Ok, here you go:  The file
   build.properties holds the general settings for building a DocBook
   file.  Platform specific values are stored in the
   build.properties.PLATFORM files.  Customization of stylesheets is
   possible.  Check out the included stylesheet for some ideas:
   `stylesheets/fo/docbook.xsl`

== Usage

=== Build Tasks
Run the following tasks the create the desired output
format, e.g. "ant pdf".  All output is stored it the directory "build",
it's customizable throught the variable "output.dir":

pdf           : create PDF output (default task)
epub          : create EPUB output
epub3         : create EPUB3 output
xhtml         : create XHTML output
xhtmlchunk    : create chunked XHTML output
xhtml5        : create XHTML5 output
xhtml5chunk   : create chunked XHTML5 output
validate      : validates the DocBook document
clean         : delete all dynamically created files/the "out" directory
test          : execute all creation tasks one after the other

=== Input Formats
It's also possible to convert files in the Asciidoc format to DocBook
and than to the different output formats.  Set property
`file.format` to `asciidoc` and change `file.suffix` to the
suffix of the input file - it's necessary because there doesn't seem to
be way to figure this out using Ant.

=== Examples
.Convert any DocBook file to PDF without editing build.properties
This takes advantage of ant's ability to specify properties on the
commmand line.

 ant -Dfile=myfile.xml pdf

.Convert this Asciidoc file to PDF
Actually, it doesn't work yet!  The reason is that Asciidoc doesn't ship
a DocBook 5 backend.  When you run this command, you can take the
resulting DocBook file (build/README.xml) and tweak it to make compile
properly.

 ant -Dfile=README.adoc -Dfile.format=asciidoc -Dfile.suffix=adoc pdf

== Additional Software Needed!
Make sure you have a working Java/Ant setup: https://www.java.com/ and
http://ant.apache.org

*In addition you need to download the software listed in file
lib/README.*

== Customization

=== Include custom Fonts
It is possible to include custom fonts into fop-generated
documents.  Follow these steps:

.Generate XML description for the custom True Type Font
Execute the following command in the fop folder `lib/fop`.  The constant
FILENAME has to be replaced by the font's filename:

 java -cp lib/commons-io-1.3.1.jar:lib/commons-logging-1.0.4.jar:build/fop.jar:lib/avalon-framework-cvs-20020806.jar:lib/xml-apis.jar:lib/xercesImpl-2.2.1.jar:lib/xalan-2.4.1.jar org.apache.fop.fonts.apps.TTFReader FILENAME.ttf FILENAME.xml

The following discussions might be of interest to you:
* Discussion at http://www.mail-archive.com/fop-user@xml.apache.org/msg13631.html
* More information at http://xmlgraphics.apache.org/fop/0.94/fonts.html#register

.Include font in fop.xconf
Add the custom font to the fonts section.  Here is an example for the
ukai font:

 <fonts>
 ...
 <font metrics-url="lib/fonts/ukai.xml" kerning="yes" embed-url="lib/fonts/ukai.ttf">
   <font-triplet name="ARPLZenKaiUni" style="normal" weight="normal"/>
   <font-triplet name="ARPLZenKaiUni" style="normal" weight="bold"/>
   <font-triplet name="ARPLZenKaiUni" style="italic" weight="normal"/>
   <font-triplet name="ARPLZenKaiUni" style="italic" weight="bold"/>
 </font>
 ...
 </fonts>

.Include font in stylesheet
Add the font to the fo-stylesheet (`stylesheets/fo/docbook.xsl`):

 <xsl:param name='title.font.family'>sans-serif,ARPLZenKaiUni</xsl:param>
 <xsl:param name='body.font.family'>serif,ARPLZenKaiUni</xsl:param>

There are even more font family parameters that can be set:

 <xsl:param name='monospace.font.family'>monospace</xsl:param>
 <xsl:param name='symbol.font.family'>Symbol,ZapfDingbats</xsl:param>

==== More to come
...

== Licensing and Copyright

  Copyright (C) 2013 Jan Christoph Ebersbach <jceb@e-jc.de>
  
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at
  
  http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.

// vi: ft=asciidoc:tw=72:sw=2:ts=4
